"""pyjj — pythonic API for Jujutsu VCS, built on pyjj_bindings."""

from pyjj_bindings import (
    # Version
    VERSION,
    # Exceptions
    JjError,
    RepoInitError,
    RepoLoadError,
    BackendError,
    IndexError,
    TransactionError,
    WorkspaceInitError,
    WorkspaceLoadError,
    WorkingCopyError,
    CheckoutError,
    RevsetParseError,
    RevsetEvalError,
    GitImportError,
    GitExportError,
    GitFetchError,
    GitPushError,
    # ID types
    CommitId,
    ChangeId,
    TreeId,
    FileId,
    Timestamp,
    Signature,
    # Core types
    UserSettings,
    Bookmark,
    Tag,
    Commit,
    DiffEntry,
    Operation,
    ReadonlyRepo,
    Transaction,
    CommitBuilder,
    Workspace,
    Hunk,
    AnnotationLine,
    AbsorbStats,
    FileToFix,
    FixSummary,
    OpAbandonStats,
    Verification,
    GraphEdge,
    GraphNode,
    Bisector,
    RunPool,
    RunSlot,
    BisectStep,
    EvolutionEntry,
    diff_hunks,
    remove_repo_config_dir,
    repo_config_repo_path,
    repo_configs_root_dir,
    VERSION,
    __version__,
)
from . import _async as _async  # noqa: F401  (installs *_async methods below)
from . import hunk as hunk  # noqa: F401

__all__ = [
    "JjError",
    "RepoInitError",
    "RepoLoadError",
    "BackendError",
    "IndexError",
    "TransactionError",
    "WorkspaceInitError",
    "WorkspaceLoadError",
    "WorkingCopyError",
    "CheckoutError",
    "RevsetParseError",
    "RevsetEvalError",
    "GitImportError",
    "GitExportError",
    "GitFetchError",
    "GitPushError",
    "CommitId",
    "ChangeId",
    "TreeId",
    "FileId",
    "Timestamp",
    "Signature",
    "UserSettings",
    "Bookmark",
    "Tag",
    "Commit",
    "DiffEntry",
    "Operation",
    "ReadonlyRepo",
    "Transaction",
    "CommitBuilder",
    "Workspace",
    "Hunk",
    "AnnotationLine",
    "AbsorbStats",
    "FileToFix",
    "FixSummary",
    "OpAbandonStats",
    "Verification",
    "GraphEdge",
    "GraphNode",
    "Bisector",
    "RunPool",
    "RunSlot",
    "BisectStep",
    "EvolutionEntry",
    "diff_hunks",
    "remove_repo_config_dir",
    "repo_config_repo_path",
    "repo_configs_root_dir",
    "hunk",
    "__version__",
]
