import argparse


def _op_help(args):
    import sys
    print("usage: pyjj op {restore}", file=sys.stderr)
    return 2


def add_parsers(sub) -> None:
    p_undo = sub.add_parser("undo", help="Undo the last operation")
    p_undo.set_defaults(_handler="pyjj_cli.commands.operation:undo")
    p_redo = sub.add_parser("redo", help="Redo a previously undone operation")
    p_redo.set_defaults(_handler="pyjj_cli.commands.operation:redo")

    p_op = sub.add_parser("op", help="Operation log commands")
    p_op.set_defaults(_handler="pyjj_cli.cli.operation:_op_help")
    op_sub = p_op.add_subparsers(dest="op_command")
    p_opr = op_sub.add_parser("restore", help="Restore to the state of an operation")
    p_opr.add_argument("operation_pos", metavar="OPERATION", help="The operation to restore to")
    p_opr.set_defaults(_handler="pyjj_cli.commands.operation:op_restore")
    p_op_log2 = op_sub.add_parser("log", help="Show the operation log")
    p_op_log2.set_defaults(_handler="pyjj_cli.commands.operation:op_log")
    p_op_show2 = op_sub.add_parser("show", help="Show changes to the repository in an operation")
    p_op_show2.add_argument("operation", nargs="?", help="Operation to show")
    p_op_show2.set_defaults(_handler="pyjj_cli.commands.operation:op_show")
    p_op_abandon2 = op_sub.add_parser("abandon", help="Abandon operation history")
    p_op_abandon2.add_argument("operations", nargs="+", help="Operations to abandon")
    p_op_abandon2.set_defaults(_handler="pyjj_cli.commands.operation:op_abandon")
    p_op_diff2 = op_sub.add_parser("diff", help="Compare changes to the repository between two operations")
    p_op_diff2.add_argument("from", help="From operation")
    p_op_diff2.add_argument("to", help="To operation")
    p_op_diff2.set_defaults(_handler="pyjj_cli.commands.operation:op_diff")
    p_op_integrate2 = op_sub.add_parser("integrate", help="Make an operation part of the operation log")
    p_op_integrate2.add_argument("operation", help="Operation to integrate")
    p_op_integrate2.set_defaults(_handler="pyjj_cli.commands.operation:op_integrate")
    p_op_revert2 = op_sub.add_parser("revert", help="Create a new operation that reverts an earlier operation")
    p_op_revert2.add_argument("operation", help="Operation to revert")
    p_op_revert2.set_defaults(_handler="pyjj_cli.commands.operation:op_revert")

    p_oplog = sub.add_parser("operation", help="Commands for working with the operation log")
    p_oplog.set_defaults(_handler="pyjj_cli.cli.operation:_op_help")
    oplog_sub = p_oplog.add_subparsers(dest="oplog_command")
    p_oplog_log = oplog_sub.add_parser("log", help="Show the operation log")
    p_oplog_log.set_defaults(_handler="pyjj_cli.commands.operation:op_log")
    p_oplog_show = oplog_sub.add_parser("show", help="Show changes to the repository in an operation")
    p_oplog_show.add_argument("operation", nargs="?", help="Operation to show")
    p_oplog_show.set_defaults(_handler="pyjj_cli.commands.operation:op_show")
    p_oplog_abandon = oplog_sub.add_parser("abandon", help="Abandon operation history")
    p_oplog_abandon.add_argument("operations", nargs="+", help="Operations to abandon")
    p_oplog_abandon.set_defaults(_handler="pyjj_cli.commands.operation:op_abandon")
    p_oplog_diff = oplog_sub.add_parser("diff", help="Compare changes to the repository between two operations")
    p_oplog_diff.add_argument("from", help="From operation")
    p_oplog_diff.add_argument("to", help="To operation")
    p_oplog_diff.set_defaults(_handler="pyjj_cli.commands.operation:op_diff")
    p_oplog_restore2 = oplog_sub.add_parser("restore", help="Restore to the state of an operation")
    p_oplog_restore2.add_argument("operation", help="Operation to restore to")
    p_oplog_restore2.set_defaults(_handler="pyjj_cli.commands.operation:op_restore")
    p_oplog_integrate = oplog_sub.add_parser("integrate", help="Make an operation part of the operation log")
    p_oplog_integrate.add_argument("operation", help="Operation to integrate")
    p_oplog_integrate.set_defaults(_handler="pyjj_cli.commands.operation:op_integrate")
    p_oplog_revert = oplog_sub.add_parser("revert", help="Create a new operation that reverts an earlier operation")
    p_oplog_revert.add_argument("operation", help="Operation to revert")
    p_oplog_revert.set_defaults(_handler="pyjj_cli.commands.operation:op_revert")

    p_evolog = sub.add_parser("evolog", help="Show how a change has evolved over time")
    p_evolog.add_argument("-r", "--revisions", dest="revisions", default="@", help="Revisions to follow (default: @)")
    p_evolog.add_argument("-n", "--limit", dest="limit", type=int, default=None, help="Limit number of revisions")
    p_evolog.set_defaults(_handler="pyjj_cli.commands.operation:evolog")

    p_next = sub.add_parser("next", help="Move the working-copy commit to the child revision")
    p_next.add_argument("amount", nargs="?", type=int, default=1, help="Number of revisions to move")
    p_next.set_defaults(_handler="pyjj_cli.commands.operation:next_commit")

    p_prev = sub.add_parser("prev", help="Change the working copy revision relative to the parent revision")
    p_prev.add_argument("amount", nargs="?", type=int, default=1, help="Number of revisions to move")
    p_prev.set_defaults(_handler="pyjj_cli.commands.operation:prev_commit")

    p_par = sub.add_parser("parallelize", help="Parallelize revisions by making them siblings")
    p_par.set_defaults(_handler="pyjj_cli.commands.operation:parallelize")
    p_inter = sub.add_parser("interdiff", help="Show differences between the diffs of two revisions")
    p_inter.set_defaults(_handler="pyjj_cli.commands.operation:interdiff")
